Bring in all v6.0.0 files

diff --git a/libexec/tgenv-use b/libexec/tgenv-use
--- a/libexec/tgenv-use
+++ b/libexec/tgenv-use
@@ -9,12 +9,26 @@ declare version_requested version regex
 
 version_requested="${1}"
 
+if [[ "${version_requested}" =~ ^min-required$ ]]; then
+  echo "Detecting minimal required version..."
+  found_min_required="$(tgenv-min-required)"
+
+  if [[ $? -eq 0 ]]; then
+      echo "Min required version is detected as ${found_min_required}"
+      version_requested="${found_min_required}"
+  else
+    echo "Min required version is currently not supported by terragrunt"
+    exit 1
+  fi
+fi
+
 if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
   version="${version_requested%%\:*}"
   regex="${version_requested##*\:}"
 elif [[ "${version_requested}" =~ ^latest$ ]]; then
   version="${version_requested}"
   regex="^[0-9]\+\.[0-9]\+\.[0-9]\+$"
+  #regex=""
 else
   version="${version_requested}"
   regex="^${version_requested}$"
